<a href="https://colab.research.google.com/github/MR-SAMIR21/Data-Science/blob/main/3rd_jul_class_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Crash Course**

In [ ]:
import numpy as np

In [ ]:
import sys
sys.version

'3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]'

In [ ]:
np.__version__

'2.0.2'

In [ ]:
# create list

my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [ ]:
type(my_list)

list

# **below code we are converting list to array**

In [ ]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [ ]:
np.arange(10,30,5,3)

TypeError: Cannot interpret '3' as a data type

In [ ]:
np.arange(8, 20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,8)

array([], dtype=int64)

In [ ]:
np.arange(-20,8) # 1st arg < 2nd arg

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [ ]:
n = np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [ ]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))  # 2d array

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,3,), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
nd = np.zeros((5,9) , dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [ ]:
nd1 = np.ones((10,10), dtype = int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.three(3)

AttributeError: module 'numpy' has no attribute 'three'