<a href="https://colab.research.google.com/github/MR-SAMIR21/Data-Science/blob/main/T11_4th_jul_NumPy_Crash_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
import sys
sys.version

'3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]'

# **Creating Arrays**

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10)  # 1st arg < 2nd arg

array([], dtype=int64)

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [20]:
np.arange(300,20)

array([], dtype=int64)

In [21]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,10)

array([], dtype=int64)

In [23]:
np.arange(10,30,5)# 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [25]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

## **zeros**

In [26]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [27]:
np.zeros(5, dtype=int) # hyperparameter tuning

array([0, 0, 0, 0, 0])

In [28]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [29]:
zero = np.zeros([2,2,])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [30]:
ero = np.zeros([2,2,])
print(zero)

print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [31]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [35]:
np.zeros((5,10)) # bydefault 1 arg--will give row & 2nd arg-columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) #  parameter tuniing

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [37]:
print(np.zeros(n,dtype=int))  ## hyperparameter tuning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [38]:
n

(6, 7)

In [39]:
n1

(6, 8)

In [40]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
np.ones(3)

array([1., 1., 1.])

In [42]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [43]:
np.ones(4)

array([1., 1., 1., 1.])

In [44]:
n

(6, 7)

In [45]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.ones((5,4),dtype=int)# by default 5-rows & 4-columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [48]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
np.ones(2)

In [ ]:
np.ones((2,4))

In [49]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [50]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.three((2,4))

# **range()**

In [ ]:
range(5)

In [51]:
r = range(5)
r

range(0, 5)

In [52]:
for i in r:
  print(i)

0
1
2
3
4


In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
range(1,10)

range(1, 10)

In [55]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
list(range(1,10,3))

[1, 4, 7]

In [57]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# **random()**

In [58]:
rand(3,2)

NameError: name 'rand' is not defined

In [59]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [60]:
np.random.rand(5)

array([0.77378971, 0.95563577, 0.60374301, 0.41963675, 0.00916128])

In [61]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(2,4)

In [62]:
np.random.randint(2,4)

2

In [63]:
np.random.randint(2,10) # 2nd argument is exclusive

5

In [64]:
np.random.randint(0,1)

0

In [65]:
np.random.randint(10,20,5)

array([14, 13, 17, 11, 13])

In [66]:
np.random.randint(1,6,4)

array([4, 4, 4, 4])

In [67]:
np.random.rand(3)

array([0.82221355, 0.5821971 , 0.46304445])

In [68]:
np.random.randint(1)

0

In [69]:
np.random.randint(30,20,10)

ValueError: low >= high

In [ ]:
np.random.randint(-30,20,10)

In [ ]:
np.random.randint(20,30,10)

In [ ]:
np.random.randint(5,9)# GET THE VALUE <=5 & >=9

In [70]:
np.random.randint(10,21,3)

array([16, 10, 12])

In [71]:
np.random.randint(1,12,10)

array([ 2,  4,  5, 11,  1,  5,  1,  8,  1,  1])

In [72]:
np.random.randint(10,40,(10,10)) # generate the element 10-40 with 10x10 matrix

array([[20, 32, 14, 20, 13, 31, 39, 32, 33, 11],
       [30, 24, 24, 29, 17, 16, 24, 13, 24, 24],
       [20, 26, 31, 14, 18, 38, 16, 13, 14, 30],
       [23, 22, 11, 36, 34, 20, 22, 31, 34, 35],
       [30, 26, 34, 22, 32, 19, 27, 27, 14, 29],
       [24, 22, 12, 12, 36, 25, 35, 14, 13, 25],
       [36, 29, 26, 38, 22, 26, 15, 24, 31, 11],
       [37, 11, 18, 27, 37, 29, 29, 32, 15, 27],
       [19, 35, 31, 32, 28, 15, 12, 28, 37, 29],
       [31, 30, 37, 31, 18, 32, 18, 17, 36, 36]])

In [73]:
np.random.randint(1,100,(12,12))# generate the element 1-100 with 12x12 matrix

array([[28, 91, 85, 76, 43, 19,  8, 38, 68, 90, 41, 99],
       [42, 46, 12, 54, 95, 45, 96, 46, 76, 50, 68, 54],
       [36, 55, 25, 49, 55, 53, 39, 23, 74, 58,  6, 47],
       [96, 22, 48, 97, 13, 22, 67, 23, 14, 85, 54, 92],
       [88, 75, 64, 26, 27, 20, 24, 56, 99, 70, 14, 56],
       [51, 48, 39, 68, 90, 72, 62, 41, 17, 90, 37, 28],
       [44, 93, 55, 47, 81, 43, 40, 85, 73, 63, 10, 50],
       [ 8, 18, 94, 99, 48, 81, 41, 77,  3, 33, 81,  3],
       [12,  9, 78, 37, 30,  7, 65, 47, 26, 56, 54,  1],
       [52, 46, 13, 46, 34, 73,  4, 79, 98, 69, 57, 28],
       [75, 40, 50, 83, 69, 16, 81, 82, 70,  8, 89, 41],
       [ 7, 43, 26, 81, 56, 16, 51,  8, 59, 28, 69, 72]])

In [74]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [76]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [77]:
type(b)

numpy.ndarray

In [78]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [79]:
b[:]

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [80]:
b[1:3]

array([[16, 14, 12, 13],
       [10, 11, 12, 17]])

In [81]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [82]:
b[1:2]

array([[16, 14, 12, 13]])

In [83]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [84]:
b[1,3]

np.int64(13)

In [85]:
b[1,-1]

np.int64(13)

In [86]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [87]:
b[2:3]

array([[10, 11, 12, 17]])

In [88]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [89]:
b[0:-2]

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17]])

In [90]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [91]:
b[0,2]

np.int64(16)

In [92]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [93]:
b[-5,-3]

np.int64(16)

In [94]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [95]:
b[-4,-2]

np.int64(12)

In [96]:
np.random.randint(10,20,(4,4))

array([[13, 14, 18, 18],
       [12, 11, 18, 18],
       [11, 12, 17, 13],
       [19, 18, 15, 10]])

In [97]:
b

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

In [98]:
b[-4,-2]

np.int64(12)

In [99]:
b[:]

array([[13, 16, 16, 17],
       [16, 14, 12, 13],
       [10, 11, 12, 17],
       [16, 11, 16, 11],
       [16, 12, 19, 13]])

# **Operations**

In [100]:
a = np.random.randint(10,20,10)
a

array([13, 10, 17, 17, 16, 16, 18, 17, 13, 15])

In [101]:
id(a)

137005937537360

In [102]:
arr

array([0, 1, 2, 3, 4, 5])

In [103]:
arr2 = np.random.randint(0,100,(10,10))

In [104]:
arr2

array([[65, 31, 48, 54, 42, 34, 78, 90, 95, 69],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [30, 48, 81, 29, 42, 36, 80, 14, 29, 32],
       [26, 77,  0,  2, 25, 96, 94, 64, 38,  7]])

In [105]:
arr

array([0, 1, 2, 3, 4, 5])

In [106]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr[:4]

array([0, 1, 2, 3])

In [109]:
arr2[:]

array([[65, 31, 48, 54, 42, 34, 78, 90, 95, 69],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [30, 48, 81, 29, 42, 36, 80, 14, 29, 32],
       [26, 77,  0,  2, 25, 96, 94, 64, 38,  7]])

In [110]:
arr2[0:5]

array([[65, 31, 48, 54, 42, 34, 78, 90, 95, 69],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45]])

In [111]:
arr2

array([[65, 31, 48, 54, 42, 34, 78, 90, 95, 69],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [30, 48, 81, 29, 42, 36, 80, 14, 29, 32],
       [26, 77,  0,  2, 25, 96, 94, 64, 38,  7]])

In [112]:
arr2[1,4]

np.int64(84)

In [113]:
arr2[-5,5]

np.int64(39)

In [114]:
arr2[-5,-5]

np.int64(39)

In [115]:
arr2

array([[65, 31, 48, 54, 42, 34, 78, 90, 95, 69],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [30, 48, 81, 29, 42, 36, 80, 14, 29, 32],
       [26, 77,  0,  2, 25, 96, 94, 64, 38,  7]])

In [116]:
arr2[-1,-2]

np.int64(38)

In [117]:
arr2[::-1]

array([[26, 77,  0,  2, 25, 96, 94, 64, 38,  7],
       [30, 48, 81, 29, 42, 36, 80, 14, 29, 32],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [65, 31, 48, 54, 42, 34, 78, 90, 95, 69]])

In [118]:
arr2

array([[65, 31, 48, 54, 42, 34, 78, 90, 95, 69],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [30, 48, 81, 29, 42, 36, 80, 14, 29, 32],
       [26, 77,  0,  2, 25, 96, 94, 64, 38,  7]])

In [119]:
arr2[::-2]

array([[26, 77,  0,  2, 25, 96, 94, 64, 38,  7],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57]])

In [120]:
arr2

array([[65, 31, 48, 54, 42, 34, 78, 90, 95, 69],
       [86, 92,  0, 55, 84, 20, 39, 18, 28, 57],
       [18, 70, 54,  8, 91, 18, 73, 11, 60,  2],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [95, 56, 65, 73, 62, 33,  0, 79, 94, 45],
       [ 0, 52, 73, 27, 94, 39, 31, 68,  5, 54],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [24, 82, 98,  0, 73, 19, 61, 17,  4, 69],
       [30, 48, 81, 29, 42, 36, 80, 14, 29, 32],
       [26, 77,  0,  2, 25, 96, 94, 64, 38,  7]])

In [121]:
arr2[::-3]

array([[26, 77,  0,  2, 25, 96, 94, 64, 38,  7],
       [77, 26, 10, 70, 41,  1, 67, 32,  0, 25],
       [ 0,  3, 77, 92,  5, 96, 80, 49, 18, 60],
       [65, 31, 48, 54, 42, 34, 78, 90, 95, 69]])

In [123]:
arr

array([0, 1, 2, 3, 4, 5])

In [124]:
arr.max()

np.int64(5)

In [125]:
arr.min()

np.int64(0)

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [127]:
arr.mean()

np.float64(2.5)

In [128]:
arr

array([0, 1, 2, 3, 4, 5])

In [129]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [130]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# without work on import* can you please find the median , mode  **bold text**

In [131]:
arr

array([0, 1, 2, 3, 4, 5])

In [132]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [133]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [134]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [135]:
arr

array([0, 1, 2, 3, 4, 5])

In [136]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [137]:
arr

array([0, 1, 2, 3, 4, 5])

In [138]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [139]:
arr.reshape(2,3,order='F') # print element wiht fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [140]:
arr.reshape(2,3,order='A')# A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [141]:
arr

array([0, 1, 2, 3, 4, 5])

In [142]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [143]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [144]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [145]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [147]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [148]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [149]:
arr

array([0, 1, 2, 3, 4, 5])

In [150]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# **Indexing**

In [153]:
mat = np.arange(0,100).reshape(10,10)

In [154]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [155]:
row = 4
col = 5

In [156]:
col

5

In [157]:
row

4

In [158]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [159]:
mat[row,col]

np.int64(45)

In [160]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
col = 6

In [162]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [163]:
mat[6] # bydefault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [164]:
# with slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [165]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [167]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [168]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [172]:
row

4

In [173]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [175]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [177]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [180]:
row

4

In [181]:
col

6

In [182]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [183]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[1,4]

np.int64(14)

In [185]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [186]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [187]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [192]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [193]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [194]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [204]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [206]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat[2:6,2:4] #2:6 --> only row part /// 2:4 --> it indicate only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [208]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[0,1]

np.int64(1)

In [210]:
mat[1,6]

np.int64(16)

In [211]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [213]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [216]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [217]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [218]:
mat[3,5]

np.int64(35)

In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
mat[1:2,2:4]

array([[12, 13]])

In [221]:
mat[2:3,2:3]

array([[22]])

In [223]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [224]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [225]:
mat[2:3,4:5]

array([[24]])

# **Masking / filter**

In [226]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
id(mat)

137005935243024

In [228]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [229]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [230]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [231]:
mat[mat==50]

array([50])

In [232]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [233]:
mat[mat==50]

array([50])

In [234]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [237]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [238]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [240]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [241]:
a4 = mat[mat==50]
a4

array([50])

# **python program to generate otp**

In [242]:
import random

def generate_otp(length=4):
  """Generate a numeric OTP of a specified length. """
  digits = '0,1,2,3,4,5'
  otp = ''.join(random.choice(digits) for _ in range(length))
  return OTP

  # Example usage
  otp_length = 4 #You can change this to any length you prefer
  otp = generate_otp(otp_length)
  print(f"Your OTP is: {otp}")

In [243]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [244]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [245]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x7c9b2db6efc0>


In [246]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
